DROP DATABASE IF EXISTS Exam;
CREATE DATABASE Exam;
USE Exam;

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER(
CustomerID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR (50) NOT NULL,
Phone CHAR (16),
Email VARCHAR (50) NOT NULL,
Address VARCHAR (200) NOT NULL,
Note VARCHAR (200) NOT NULL
);

DROP TABLE IF EXISTS CAR;
CREATE TABLE CAR (
CarID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Maker ENUM("HONDA","TOYOTA","NISSAN"),
Model VARCHAR (30) NOT NULL,
Year YEAR,
Color VARCHAR (30),
Note VARCHAR (50) 
);

DROP TABLE IF EXISTS CAR_ORDER;
CREATE TABLE CAR_ORDER(
OrderID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
CustomerID TINYINT UNSIGNED,
CarID TINYINT UNSIGNED,
Amount TINYINT UNSIGNED DEFAULT 1,
SalePrice INT UNSIGNED,
OrderDate DATE,
DeliveryDate DATE, 
DeliveryAddress VARCHAR (50),
Status ENUM("0","1","2"), -- (0: đã đặt hàng, 1: đã giao, 2: đã hủy)
Note VARCHAR (50),
FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID) ,
FOREIGN KEY (CarID) REFERENCES CAR(CarID)
);